import { describe, expect, it } from "vitest";
import { defaultConfig, makeConfig } from "./config.js";

describe("defaultConfig", () => {
  it("has the specified defaults", () => {
    expect(defaultConfig).toEqual({
      pageCap: 500,
      crawlDelayMs: 500,
      userAgent: "LinkLensBot/0.1 (+https://github.com/sneha-860/LinkLens)",
      epsilon: 0.2,
      refExplainTerms: 10,
      refPrefilter: "none",
      lshNumPerm: 128,
      lshPartitions: 16,
      lshMaxRows: 16,
      lshThreshold: 0.1,
      lshFalsePositiveWeight: 0.5,
      lshFalseNegativeWeight: 0.5,
      lshEvalCaps: [500, 1000, 2000],
      lshEvalThresholds: [0.05, 0.1, 0.2],
      lshEvalRepeats: 3,
      alpha: 0.1,
      frequentNgramDropPct: 0.07,
      frequentNgramMinDf: 2,
      frequentNgramMinDocShare: 0.5,
      textMinTokenLength: 2,
      textMaxNgram: 2,
      embeddingModel: "Xenova/all-MiniLM-L6-v2",
      embeddingDtype: "fp32",
      embeddingBodyTokens: 256,
      embeddingBatchSize: 16,
      pagerankDamping: 0.85,
      randomSeed: 42,
      robotsMaxBytes: 512_000,
      robotsMaxRedirects: 5,
      robotsFetchTimeoutMs: 10_000,
      fetchTimeoutMs: 15_000,
      maxRedirects: 10,
      maxBodyBytes: 10_485_760,
      fetchMaxRetries: 2,
      retryBackoffMs: 1_000,
      crawlJobLockMs: 30_000,
      crawlConcurrency: 1,
      includeSubdomains: false,
      maxCrawlDelayMs: 60_000,
      robotsCacheTtlMs: 86_400_000,
      robotsUnreachableGraceDays: 30,
      robotsTreat429AsUnreachable: false,
      followNofollow: true,
      storeRawHtml: true,
      canonicalMaxHops: 3,
      pagerankTolerance: 1e-10,
      pagerankMaxIterations: 1_000,
      betweennessExactMaxNodes: 300,
      betweennessSamples: 100,
      discoveryMaxFetches: 100,
      sitemapMaxDepth: 3,
      sitemapMaxUrls: 50_000,
      storeDiscoveryBodies: true,
      prominenceRegionWeights: {
        body: 1.0,
        breadcrumb: 0.5,
        aside: 0.4,
        header: 0.3,
        nav: 0.3,
        pagination: 0.2,
        footer: 0.1,
      },
      prominencePositionDecay: 0.1,
      prominenceSitewideShare: 0.5,
      prominenceSitewideDiscount: 0.3,
      candidateMaxPerTarget: 30,
      candidateUtilityPatterns: [
        "(^|/)(log-?in|sign-?in|log-?out|sign-?out|register|sign-?up)([/.?]|$)",
        "(^|/)(cart|basket|checkout)([/.?]|$)",
        "(^|/)(my-?)?(account|profile)s?([/.?]|$)",
        "(^|/)search([/.?]|$)",
        "[?&](q|s|query|search)=",
        "(^|/)tags?/",
      ],
      candidateSectionBlocking: true,
      candidateSiblingSections: [],
      candidateTopLevelIsSibling: true,
      candidateRequireRef: true,
      counterfactualWorkers: 0,
      counterfactualValidationSample: 5,
      sigmaVariant: "refGateCosine",
      sigmaBlendLambda: 0.5,
      fixTopK: 10,
      e3TopKs: [10, 25, 50],
      e3RandomDraws: 20,
      e4RecrawlDays: 14,
      e5LargeShare: 0.1,
      e5LargeMin: 3,
      e5InlinkMinAbsDiff: 2,
      e5InlinkMinRelDiff: 0.5,
      e5Examples: 3,
      e6MaskShareMin: 0.1,
      e6MaskShareMax: 0.2,
      e6Repeats: 5,
      e6Ks: [5, 10, 20],
      e6StripAnchorsFromBody: true,
      e6GraphBaselines: true,
      e7Epsilons: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4],
      e7Alphas: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3],
      rescueTopK: 5,
      rescueMaxFetches: 50,
      explainTerms: 5,
      anchorExcerptChars: 240,
      ratingPoolSize: 50,
      ratingSampleSize: 50,
      ratingKs: [5, 10, 25, 50],
      proxyBootstrap: 2000,
      proxyMinEdgesPerSource: 3,
      linkHealthMinChainHops: 2,
      pageTypeRules: defaultConfig.pageTypeRules,
      pageTypePriors: {
        homepage: 1,
        product: 0.8,
        hub: 0.7,
        article: 0.6,
        other: 0.4,
        utility: 0.05,
      },
      importanceWeights: { typePrior: 0.4, pagerank: 0.25, depth: 0.2, inboundBodyLinks: 0.15 },
      fixScoring: "S",
      l13Repeats: 2,
      l13Lightgbm: defaultConfig.l13Lightgbm,
      l13ShapTop: 3,
      auditDeepPageDepth: 3,
      auditDeepPageHighDepth: 6,
      auditWeakAuthorityPercentile: 20,
      auditWeakAuthorityHighPercentile: 5,
      apiMaxConcurrentAudits: 2,
      apiAuditLeaseMs: 30_000,
      apiStageWorkers: 2,
    });
  });

  it("is frozen", () => {
    expect(Object.isFrozen(defaultConfig)).toBe(true);
  });
});

describe("makeConfig", () => {
  it("returns defaults when given no overrides", () => {
    expect(makeConfig()).toEqual(defaultConfig);
  });

  it("applies overrides and freezes the result", () => {
    const cfg = makeConfig({ epsilon: 0.3 });
    expect(cfg.epsilon).toBe(0.3);
    expect(cfg.pageCap).toBe(500);
    expect(Object.isFrozen(cfg)).toBe(true);
  });

  it.each([
    [{ epsilon: 1.5 }],
    [{ alpha: -0.1 }],
    [{ pagerankDamping: 2 }],
    [{ pageCap: 0 }],
    [{ pageCap: 10.5 }],
    [{ crawlDelayMs: -1 }],
    [{ userAgent: " " }],
    [{ robotsMaxBytes: 1024 }],
    [{ robotsMaxRedirects: 4 }],
    [{ robotsFetchTimeoutMs: 0 }],
    [{ fetchTimeoutMs: 0 }],
    [{ maxRedirects: -1 }],
    [{ fetchMaxRetries: 1.5 }],
    [{ crawlConcurrency: 0 }],
    [{ includeSubdomains: "yes" as unknown as boolean }],
    [{ followNofollow: 1 as unknown as boolean }],
    [{ maxCrawlDelayMs: 0 }],
    [{ robotsCacheTtlMs: 25 * 60 * 60 * 1000 }],
    [{ robotsUnreachableGraceDays: 0 }],
    [{ canonicalMaxHops: 0 }],
    [{ pagerankTolerance: 0 }],
    [{ pagerankMaxIterations: 0 }],
    [{ betweennessSamples: 0 }],
    [{ discoveryMaxFetches: 0 }],
    [{ sitemapMaxDepth: -1 }],
    [{ auditDeepPageHighDepth: 2 }],
    [{ auditWeakAuthorityPercentile: 101 }],
    [{ auditWeakAuthorityHighPercentile: 30 }],
    [{ frequentNgramMinDf: 0 }],
    [{ frequentNgramMinDocShare: 1.5 }],
    [{ crawlJobLockMs: 0 }],
    [{ apiMaxConcurrentAudits: 0 }],
    [{ apiAuditLeaseMs: 0 }],
    [{ apiStageWorkers: -1 }],
    [{ textMinTokenLength: 0 }],
    [{ textMaxNgram: 1.5 }],
    [{ refExplainTerms: 0 }],
    [{ refPrefilter: "minhash" as never }],
    [{ lshNumPerm: 0 }],
    [{ lshMaxRows: 200 }],
    [{ lshThreshold: 0 }],
    [{ lshFalsePositiveWeight: 0, lshFalseNegativeWeight: 0 }],
    [{ lshEvalCaps: [500, 500] }],
    [{ lshEvalThresholds: [1.5] }],
    [{ lshEvalRepeats: 0 }],
    [{ embeddingBodyTokens: 0 }],
    [{ embeddingBatchSize: 0 }],
    [{ embeddingDtype: "fp64" as never }],
    [{ prominencePositionDecay: -0.1 }],
    [{ candidateMaxPerTarget: 0 }],
    [{ sigmaVariant: "cosine" as never }],
    [{ sigmaBlendLambda: 1.2 }],
    [{ fixTopK: 0 }],
    [{ e3TopKs: [] }],
    [{ e3TopKs: [10, 10] }],
    [{ e3TopKs: [0] }],
    [{ e3RandomDraws: 0 }],
    [{ e4RecrawlDays: 0 }],
    [{ e5LargeShare: 1.5 }],
    [{ e5LargeMin: 0 }],
    [{ e5InlinkMinRelDiff: -0.1 }],
    [{ e6MaskShareMin: 0.3, e6MaskShareMax: 0.2 }],
    [{ e6Repeats: 0 }],
    [{ e6Ks: [0] }],
    [{ e7Epsilons: [] }],
    [{ e7Epsilons: [0.1, 0.1] }],
    [{ e7Alphas: [1.5] }],
    [{ rescueTopK: 0 }],
    [{ explainTerms: 0 }],
    [{ explainTerms: 11 }],
    [{ anchorExcerptChars: 0 }],
    [{ ratingSampleSize: 60 }],
    [{ ratingKs: [0] }],
    [{ proxyBootstrap: 0 }],
    [{ proxyMinEdgesPerSource: 0 }],
    [{ linkHealthMinChainHops: 0 }],
    [{ l13Repeats: 0 }],
    [{ l13Repeats: 9 }],
    [{ l13Lightgbm: { num_leaves: Number.NaN } }],
    [{ l13ShapTop: 0 }],
    [{ rescueMaxFetches: 0 }],
    [{ counterfactualWorkers: -1 }],
    [{ counterfactualValidationSample: 1.5 }],
    [{ candidateUtilityPatterns: ["(unclosed"] }],
    [{ candidateSiblingSections: [["blog", ""]] }],
    [{ candidateSectionBlocking: "yes" as never }],
    [{ prominenceSitewideShare: 1.5 }],
    [{ prominenceSitewideDiscount: -1 }],
    [{ prominenceRegionWeights: { ...defaultConfig.prominenceRegionWeights, footer: -1 } }],
    [{ prominenceRegionWeights: { ...defaultConfig.prominenceRegionWeights, main: 1 } as never }],
    [{ prominenceRegionWeights: { body: 1 } as never }],
  ])("rejects invalid override %o", (overrides) => {
    expect(() => makeConfig(overrides)).toThrow(RangeError);
  });
});
